export const CALL_API = 'API';
export const NOTIFICATIONS_MASK = 'NOTIFICATIONS_MASK';
export const NOTIFICATIONS_MASK_REMOVE = 'NOTIFICATIONS_MASK_REMOVE';
export const NOTIFICATIONS_ALERT = 'NOTIFICATIONS_ALERT';
